#include "config.h"

#if USE_stdlib
#include <stdlib.h>
#endif
#include <ctype.h>

#include "structs.h"
#include "parse.h"
#include "cmdtab.h"
#include "channels.h"
#include "act.h"
#include "track.h"
#include "proto.h"
#include "utility.h"

/* forward declarations */
extern struct pos_struct pos_list[];
extern struct set_struct gcmd_list[];
extern struct command_info cmd_list[];
static parse_table* parse_commands;

int command_hash(char data);

void assign_command_pointers(void)
{
  struct command_info*	ptr;

  parse_commands = MakeParseTable(command_hash(0), command_hash);

  for(ptr = cmd_list ; ptr->name ; ptr++)
    AddParseEntry(parse_commands, ptr->name, (void*) ptr);
}

struct command_info* lookup_command(char* command, int exact)
{
  return (struct command_info*) FindParseEntry(parse_commands, command, exact);
}

int command_hash(char data)
{
  // Solaar: added null condition
  if(data == NULL)
  {
    slog( "ERROR: null value passed to command_hash in cmdtab.c.");
    return 41;
  }
  if(data == 0)
    return 42;

  switch(data)
  {
  case 0:	return 42;
  case '\'':    return 36;
  case '@':	return 37;
  case ' ':	return 38;
  case ':':	return 39;
  case '*':	return 40;
  default:
    if(islower(data))
      return data - 'a';
    else if(isdigit(data))
      return data - '0' + 26;
/*
    sprintf(buf, "illegal character in hash: %c(%o)", data, data);
    log(buf);
*/
    return 41;
  }
}



struct pos_struct pos_list[] = {
  {"project_manager",PROJECT_MANAGER,ALL_GCMD,10},
  {"assistant_manager",ASSISTANT_MANAGER,ALL_GCMD,10},
  {"head_builder",HEAD_BUILDER,GCMD_HEADBUILD,9},
  {"head_questor",HEAD_QUESTOR,GCMD_HEADQUEST,9},
  {"coder",CODER,GCMD_CODER,7},
  {"builder",BUILDER,GCMD_BUILDER,5},
  {"ambassador",AMBASSADOR,GCMD_AMBASS,2},
  {"questor",QUESTOR,GCMD_QUESTOR,4},
  {"newbie_helper",NEWBIE_HELPER,GCMD_NEWHELP,1},
  {"webmaster",WEBMASTER,GCMD_NEWHELP,3},
  {"senior_coder",SENIOR_CODER,GCMD_SENCODER,8},
  {"senior_builder",SENIOR_BUILDER,GCMD_SENBUILDER,6},
  {"damned",DAMNED,GCMD_DAMNED,1},
  {"noposition",NOPOSITION,0,0},
  { 0 }
};

struct set_struct gcmd_list[] = {
  {"wizset",	GCMD_WIZSET},
  {"general",	GCMD_GEN},
  {"redit",	GCMD_REDIT},
  {"restore",	GCMD_RESTORE},
  {"snoop",	GCMD_SNOOP},
  {"noshout",	GCMD_NOSHOUT},
  {"poof",	GCMD_POOF},
  {"force",	GCMD_FORCE},
  {"chpwd",	GCMD_CHPWD},
  {"set",	GCMD_SET},
  {"slay",	GCMD_SLAY},
  {"load",	GCMD_LOAD},
  {"pload",	GCMD_PLOAD},
  {"oload",	GCMD_OLOAD},
  {"transfer",	GCMD_TRANS},
  {"purge",	GCMD_PURGE},
  {"shutdown",	GCMD_SHUTDOWN},
  {"string",	GCMD_STRING},
  {"switch",	GCMD_SWITCH},
  {"system",	GCMD_SYSTEM},
  {"freeze",	GCMD_FREEZE},
  {"absolve",	GCMD_ABSOLVE},
  {"stealth",	GCMD_STEALTH},
  {"show",	GCMD_SHOW},
  {"player",	GCMD_PLAYER},
  {"ban",	GCMD_BAN},
  {"stat",	GCMD_STAT},
  {"advance",	GCMD_ADVANCE},
  {"judge",	GCMD_JUDGE},
  {"echo",	GCMD_ECHO},
  {"high",	GCMD_HIGH},
  {"reimb",	GCMD_REIMB},
  { 0 }
};


struct command_info cmd_list[] = {
  { "north", 1, POSITION_STANDING, do_move, 0, 0 },
  { "east", 2, POSITION_STANDING, do_move, 0, 0 },
  { "south", 3, POSITION_STANDING, do_move, 0, 0 },
  { "west", 4, POSITION_STANDING, do_move, 0, 0 },
  { "up", 5, POSITION_STANDING, do_move, 0, 0 },
  { "down", 6, POSITION_STANDING, do_move, 0, 0 },
  { "enter", 7, POSITION_FIGHTING, do_enter, 0, 0 },
  { "exits", 8, POSITION_RESTING, do_exits, 0, 0 },
  { "kiss", 9, POSITION_RESTING, do_action, 0, 0 },
  { "get", CMD_GET, POSITION_RESTING, do_get, 0, 0 },
  { "drink", 11, POSITION_RESTING, do_drink, 0, 0 },
  { "eat", 12, POSITION_RESTING, do_eat, 0, 0 },
  { "wear", 13, POSITION_RESTING, do_wear, 0, 0 },
  { "wield", 14, POSITION_RESTING, do_wield, 0, 0 },
  { "look", 15, POSITION_RESTING, do_look, 0, 0 },
  { "score", 16, POSITION_DEAD, do_score, 0, 0 },
  { "say", CMD_SAY, POSITION_RESTING, do_say, 0, 0 },
  { "shout", 18, POSITION_RESTING, do_comm, 2, 0 },
  { "tell", 19, POSITION_RESTING, do_tell, 0, 0 },
  { "inventory", 20, POSITION_DEAD, do_inventory, 0, 0 },
  { "qui", 21, POSITION_DEAD, do_qui, 0, 0 },
  { "bounce", 22, POSITION_STANDING, do_action, 0, 0 },
  { "smile", 23, POSITION_RESTING, do_action, 0, 0 },
  { "dance", 24, POSITION_STANDING, do_action, 0, 0 },
  { "kil", 25, POSITION_FIGHTING, do_kil, 0, 0 },
  { "cackle", 26, POSITION_RESTING, do_action, 0, 0 },
  { "laugh", 27, POSITION_RESTING, do_action, 0, 0 },
  { "giggle", 28, POSITION_RESTING, do_action, 0, 0 },
  { "shake", 29, POSITION_RESTING, do_action,0,0},
  { "puke", 30, POSITION_RESTING, do_action, 0, 0 },
  { "growl", 31, POSITION_RESTING, do_action, 0, 0 },
  { "scream", 32, POSITION_RESTING, do_action, 0, 0 },
  { "insult", 33, POSITION_RESTING, do_insult, 0, 0 },
  { "comfort", 34, POSITION_RESTING, do_action, 0, 0 },
  { "nod", 35, POSITION_RESTING, do_action, 0, 0 },
  { "sigh", 36, POSITION_RESTING, do_action, 0, 0 },
  { "sulk", 37, POSITION_RESTING, do_action, 0, 0 },
  { "help", 38, POSITION_DEAD, do_help, 0, 0 },
  { "who", 39, POSITION_DEAD, do_who, 0, 0 },
  { "emote", 40, POSITION_RESTING, do_emote, 1, 0 },
  { "echo", 41, POSITION_SLEEPING, do_echo, 1, 0 },
  { "stand", 42, POSITION_RESTING, do_stand, 0, 0 },
  { "sit", 43, POSITION_RESTING, do_sit, 0, 0 },
  { "rest", 44, POSITION_RESTING, do_rest, 0, 0 },
  { "sleep", 45, POSITION_SLEEPING, do_sleep, 0, 0 },
  { "wake", 46, POSITION_SLEEPING, do_wake, 0, 0 },
  { "force", 47, POSITION_SLEEPING, do_force, 0, GCMD_FORCE },
  { "transfer", 48, POSITION_SLEEPING, do_trans, 0, GCMD_TRANS },
  { "hug", 49, POSITION_RESTING, do_action, 0, 0 },
  { "snuggle", 50, POSITION_RESTING, do_action, 0, 0 },
  { "cuddle", 51, POSITION_RESTING, do_action, 0, 0 },
  { "nuzzle", 52, POSITION_RESTING, do_action, 0, 0 },
  { "cry", 53, POSITION_RESTING, do_action, 0, 0 },
  { "news", 54, POSITION_SLEEPING, do_news, 0, 0 },
  { "equipment", 55, POSITION_SLEEPING, do_equipment, 0, 0 },
  { "buy", 56, POSITION_STANDING, do_not_here, 0, 0 },
  { "sell", 57, POSITION_STANDING, do_not_here, 0, 0 },
  { "value", 58, POSITION_STANDING, do_not_here, 0, 0 },
  { "list", 59, POSITION_STANDING, do_not_here, 0, 0 },
  { "drop", CMD_DROP, POSITION_RESTING, do_drop, 0, 0 },
  { "goto", 61, POSITION_SLEEPING, do_goto, 0, GCMD_GEN },
  { "weather", 62, POSITION_RESTING, do_weather, 0, 0 },
  { "read", 63, POSITION_RESTING, do_read, 0, 0 },
  { "pour", 64, POSITION_STANDING, do_pour, 0, 0 },
  { "grab", 65, POSITION_RESTING, do_grab, 0, 0 },
  { "remove", CMD_REMOVE, POSITION_RESTING, do_remove, 0, 0 },
  { "put", 67, POSITION_RESTING, do_put, 0, 0 },
  { "shutdow", 68, POSITION_DEAD, do_shutdow, 0, 0 },
  { "save", 69, POSITION_SLEEPING, do_save, 0, 0 },
  { "hi", 70, POSITION_FIGHTING, do_hi, 0, 0 },
  { "string", 71, POSITION_SLEEPING, do_string, 0, GCMD_STRING },
  { "give", 72, POSITION_RESTING, do_give, 0, 0 },
  { "quit", 73, POSITION_DEAD, do_quit, 0, 0 },
  { "stat", 74, POSITION_DEAD, do_stat, 0, GCMD_STAT },
  { "guard", 75, POSITION_STANDING, do_guard, 1, 0 },
  { "time", 76, POSITION_DEAD, do_time, 0, 0 },
  { "load", 77, POSITION_DEAD, do_make, 0, GCMD_LOAD },
  { "purge", 78, POSITION_DEAD, do_purge, 0, GCMD_PURGE },
  { "shutdown", 79, POSITION_DEAD, do_shutdown, 0, GCMD_SHUTDOWN },
  { "idea", 80, POSITION_DEAD, do_idea, 0, 0 },
  { "typo", 81, POSITION_DEAD, do_typo, 0, 0 },
  { "bug", 82, POSITION_DEAD, do_bug, 0, 0 },
  { "whisper", 83, POSITION_RESTING, do_whisper, 0, 0 },
  { "cast", 84, POSITION_SITTING, do_cast, 1, 0 },
  { "at", 85, POSITION_DEAD, do_at, 0, GCMD_GEN },
  { "ask", 86, POSITION_RESTING, do_ask, 0, 0 },
  { "order", 87, POSITION_RESTING, do_order, 1, 0 },
  { "sip", 88, POSITION_RESTING, do_sip, 0, 0 },
  { "taste", 89, POSITION_RESTING, do_taste, 0, 0 },
  { "snoop", 90, POSITION_DEAD, do_snoop, 0, GCMD_SNOOP },
  { "follow", 91, POSITION_RESTING, do_follow, 0, 0 },
  { "rent", 92, POSITION_STANDING, do_not_here, 1, 0 },
  { "offer", 93, POSITION_STANDING, do_not_here, 1, 0 },
  { "poke", 94, POSITION_RESTING, do_action, 0, 0 },
  { "advance", 95, POSITION_DEAD, do_advance, 0, GCMD_ADVANCE },
  { "accuse", 96, POSITION_SITTING, do_action, 0, 0 },
  { "grin", 97, POSITION_RESTING, do_action, 0, 0 },
  { "bow", CMD_BOW, POSITION_STANDING, do_action, 0, 0 },
  { "open", 99, POSITION_SITTING, do_open, 0, 0 },
  { "close", 100, POSITION_SITTING, do_close, 0, 0 },
  { "lock", 101, POSITION_SITTING, do_lock, 0, 0 },
  { "unlock", 102, POSITION_SITTING, do_unlock, 0, 0 },
  { "leave", 103, POSITION_STANDING, do_leave, 0, 0 },
  { "applaud", 104, POSITION_RESTING, do_action, 0, 0 },
  { "blush", 105, POSITION_RESTING, do_action, 0, 0 },
  { "burp", 106, POSITION_RESTING, do_action, 0, 0 },
  { "chuckle", 107, POSITION_RESTING, do_action, 0, 0 },
  { "clap", 108, POSITION_RESTING, do_action, 0, 0 },
  { "cough", 109, POSITION_RESTING, do_action, 0, 0 },
  { "curtsey", 110, POSITION_STANDING, do_action, 0, 0 },
  { "fart", 111, POSITION_RESTING, do_action, 0, 0 },
  { "flip", 112, POSITION_STANDING, do_action, 0, 0 },
  { "fondle", 113, POSITION_RESTING, do_action, 0, 0 },
  { "frown", 114, POSITION_RESTING, do_action, 0, 0 },
  { "gasp", 115, POSITION_RESTING, do_action, 0, 0 },
  { "glare", 116, POSITION_RESTING, do_action, 0, 0 },
  { "groan", 117, POSITION_RESTING, do_action, 0, 0 },
  { "grope", 118, POSITION_RESTING, do_action, 0, 0 },
  { "hiccup", 119, POSITION_RESTING, do_action, 0, 0 },
  { "lick", 120, POSITION_RESTING, do_action, 0, 0 },
  { "love", 121, POSITION_RESTING, do_action, 0, 0 },
  { "moan", 122, POSITION_RESTING, do_action, 0, 0 },
  { "nibble", 123, POSITION_RESTING, do_action, 0, 0 },
  { "pout", 124, POSITION_RESTING, do_action, 0, 0 },
  { "purr", 125, POSITION_RESTING, do_action, 0, 0 },
  { "ruffle", 126, POSITION_STANDING, do_action, 0, 0 },
  { "shiver", 127, POSITION_RESTING, do_action, 0, 0 },
  { "shrug", 128, POSITION_RESTING, do_action, 0, 0 },
  { "sing", 129, POSITION_RESTING, do_sing, 1, 0 },
  { "slap", 130, POSITION_RESTING, do_action, 0, 0 },
  { "smirk", 131, POSITION_RESTING, do_action, 0, 0 },
  { "snap", 132, POSITION_RESTING, do_action, 0, 0 },
  { "sneeze", 133, POSITION_RESTING, do_action, 0, 0 },
  { "snicker", 134, POSITION_RESTING, do_action, 0, 0 },
  { "sniff", 135, POSITION_RESTING, do_action, 0, 0 },
  { "snore", 136, POSITION_SLEEPING, do_action, 0, 0 },
  { "spit", 137, POSITION_STANDING, do_action, 0, 0 },
  { "squeeze", 138, POSITION_RESTING, do_action, 0, 0 },
  { "stare", 139, POSITION_RESTING, do_action, 0, 0 },
  { "strut", 140, POSITION_STANDING, do_action, 0, 0 },
  { "thank", 141, POSITION_RESTING, do_action, 0, 0 },
  { "twiddle", 142, POSITION_RESTING, do_action, 0, 0 },
  { "wave", 143, POSITION_RESTING, do_action, 0, 0 },
  { "whistle", 144, POSITION_RESTING, do_action, 0, 0 },
  { "wiggle", 145, POSITION_STANDING, do_action, 0, 0 },
  { "wink", 146, POSITION_RESTING, do_action, 0, 0 },
  { "yawn", 147, POSITION_RESTING, do_action, 0, 0 },
  { "snowball", 148, POSITION_STANDING, do_action, 0, 0 },
  { "write", 149, POSITION_STANDING, do_write, 1, 0 },
  { "hold", 150, POSITION_RESTING, do_grab, 1, 0 },
  { "flee", 151, POSITION_FIGHTING, do_flee, 1, 0 },
  { "sneak", 152, POSITION_STANDING, do_sneak, 1, 0 },
  { "hide", 153, POSITION_RESTING, do_hide, 1, 0 },
  { "backstab", 154, POSITION_STANDING, do_backstab, 1, 0 },
  { "pick", 155, POSITION_STANDING, do_pick, 1, 0 },
  { "steal", 156, POSITION_STANDING, do_steal, 1, 0 },
  { "bash", 157, POSITION_FIGHTING, do_bash, 1, 0 },
  { "rescue", 158, POSITION_FIGHTING, do_rescue, 1, 0 },
  { "kick", 159, POSITION_FIGHTING, do_kick, 1, 0 },
  { "french", 160, POSITION_RESTING, do_action, 0, 0 },
  { "comb", 161, POSITION_RESTING, do_action, 0, 0 },
  { "massage", 162, POSITION_RESTING, do_action, 0, 0 },
  { "tickle", 163, POSITION_RESTING, do_action, 0, 0 },
  { "practice", 164, POSITION_RESTING, do_practice, 1, 0 },
  { "pat", 165, POSITION_RESTING, do_action, 0, 0 },
  { "examine", 166, POSITION_SITTING, do_examine, 0, 0 },
  { "take", 167, POSITION_RESTING, do_get, 0, 0 },
  { "info", 168, POSITION_SLEEPING, do_info, 0, 0 },
  { "'", 169, POSITION_RESTING, do_say, 0, 0 },
  { "practise", 170, POSITION_RESTING, do_practice, 1, 0 },
  { "curse", 171, POSITION_RESTING, do_action, 0, 0 },
  { "use", 172, POSITION_SITTING, do_use, 1, 0 },
  { "where", 173, POSITION_DEAD, do_where, 1, 0 },
  { "levels", 174, POSITION_DEAD, do_levels, 0, 0 },
  { "reroll", 175, POSITION_DEAD, do_reroll, 0, GCMD_HIGH },
  { "pray", 176, POSITION_SITTING, do_action, 0, 0 },
  { "suggestion", 177, POSITION_SITTING, do_suggestion, 0, 0},
  { "beg", 178, POSITION_RESTING, do_action, 0, 0 },
  { "kill", 179, POSITION_FIGHTING, do_kill, 0, 0 },
  { "cringe", 180, POSITION_RESTING, do_action, 0, 0 },
  { "daydream", 181, POSITION_SLEEPING, do_action, 0, 0 },
  { "fume", 182, POSITION_RESTING, do_action, 0, 0 },
  { "grovel", 183, POSITION_RESTING, do_action, 0, 0 },
  { "hit", 184, POSITION_SITTING, do_hit, 0, 0 },
  { "nudge", 185, POSITION_RESTING, do_action, 0, 0 },
  { "peer", 186, POSITION_RESTING, do_action, 0, 0 },
  { "point", 187, POSITION_RESTING, do_action, 0, 0 },
  { "wonder", 188, POSITION_RESTING, do_action, 0, 0 },
  { "numberonee", 189, POSITION_RESTING, do_action, 0, 0 },
  { "snarl", 190, POSITION_RESTING, do_action, 0, 0 },
  { "prank", 191, POSITION_RESTING, do_action, 0, 0 },
  { "steam", 192, POSITION_RESTING, do_action, 0, 0 },
  { "numberfivb", 193, POSITION_RESTING, do_action, 0, 0 },
  { "numberfoua", 194, POSITION_RESTING, do_action, 0, 0 },
  { "think", 195, POSITION_RESTING, do_comm, 0, GCMD_GEN },
  { "numberthrec", 196, POSITION_RESTING, do_action, 0, 0 },
  { "worship", 197, POSITION_RESTING, do_action, 0, 0 },
  { "yodel", 198, POSITION_RESTING, do_action, 0, 0 },
  { "brief", 199, POSITION_DEAD, do_plrtog, 0, 0 },
  { "wizlist", 200, POSITION_DEAD, do_wizlistnew, 0, 0 },
  { "consider", 201, POSITION_RESTING, do_consider, 0, 0 },
  { "group", 202, POSITION_RESTING, do_group, 1, 0 },
  { "restore", 203, POSITION_DEAD, do_restore, 0, GCMD_RESTORE },
  { "return", 204, POSITION_STANDING, do_return, 0, 0 },
  { "switch", 205, POSITION_DEAD, do_switch, 0, GCMD_SWITCH },
  { "quaff", 206, POSITION_RESTING, do_quaff, 0, 0 },
  { "recite", 207, POSITION_STANDING, do_recite, 0, 0 },
  { "users", 208, POSITION_DEAD, do_users, 0, GCMD_GEN },
  { "pose", 209, POSITION_STANDING, do_pose, 0, 0 },
  { "noshout", 210, POSITION_SLEEPING, do_noshout, 0, GCMD_NOSHOUT },
  { "wizhelp", 211, POSITION_SLEEPING, do_wizhelp, 0, GCMD_GEN },
  { "credits", 212, POSITION_DEAD, do_credits, 0, 0 },
  { "compact", 213, POSITION_DEAD, do_plrtog, 0, 0 },
  { ":", 214, POSITION_RESTING, do_emote, 0, 0 },
  { "deafen", 215, POSITION_SLEEPING, do_deafen, 1, 0 },
  { "slay", 216, POSITION_STANDING, do_kill, 0, GCMD_SLAY },
  { "wimpy", 217, POSITION_DEAD, do_wimp, 0, 0 },
  { "junk", 218, POSITION_RESTING, do_junk, 1, 0 },
  { "deposit", CMD_DEPOSIT, POSITION_RESTING, do_not_here, 1, 0 },
  { "withdraw", CMD_WITHDRAW, POSITION_RESTING, do_not_here, 1, 0 },
  { "balance", 221, POSITION_RESTING, do_not_here, 1, 0 },
  { "nohassle", 222, POSITION_DEAD, do_nohassle, 0, GCMD_GEN },
  { "system", 223, POSITION_DEAD, do_system, 0, GCMD_SYSTEM },
  { "pull", 224, POSITION_STANDING, do_not_here, 1, 0 },
  { "stealth", 225, POSITION_DEAD, do_stealth, 0, GCMD_STEALTH },
  { "edit", 226, POSITION_DEAD, do_edit, 0, GCMD_REDIT },
  { "@set", 227, POSITION_DEAD, do_set, 0, GCMD_SET },
  { "rsave", 228, POSITION_DEAD, do_rsave, 0, GCMD_REDIT },
  { "rload", 229, POSITION_DEAD, do_rload, 0, GCMD_REDIT },
  { "track", 230, POSITION_STANDING, do_track, 0, 0 },
  { "wizlock", 231, POSITION_DEAD, do_wizlock, 0, GCMD_HIGH },
  { "highfive", 232, POSITION_DEAD, do_highfive, 1, 0 },
// Solaar - player base too small, worrying about title spaming is stupid. change level 21 for title to 1
  { "title", 233, POSITION_DEAD, do_title, 1, 0 },
  { "whozone", 234, POSITION_DEAD, do_who, 0, 0 },
  { "assist", 235, POSITION_FIGHTING, do_assist, 0, 0 },
  { "attribute", 236, POSITION_DEAD, do_attribute, 1, 0 },
  { "world", 237, POSITION_DEAD, do_world, 0, 0 },
  { "allspells", 238, POSITION_DEAD, do_spells, 0, 0 },
  { "breath", 239, POSITION_FIGHTING, do_breath, 0, 0 },
  { "show", 240, POSITION_DEAD, do_show, 0, GCMD_SHOW },
  { "debug", 241, POSITION_DEAD, do_debug, 0, GCMD_HIGH },
  { "invisible", 242, POSITION_DEAD, do_invis, 0, GCMD_GEN },
  { "gain", 243, POSITION_DEAD, do_gain, 1, 0 },
  { "instazone", 244, POSITION_DEAD, do_instazone, 0, GCMD_REDIT },
  { "disarm", 245, POSITION_FIGHTING, do_disarm, 1, 0 },
  { "bonk", 246, POSITION_SITTING, do_action, 1, 0 },
  { "chpwd", 247, POSITION_SITTING, do_passwd, 0, GCMD_CHPWD },
  { "fill", 248, POSITION_SITTING, do_not_here, 0, 0 },
  { "quickdraw", 249, POSITION_FIGHTING, do_quick_draw, 1, 0 },
/*  { "extraone", 250, POSITION_STANDING, do_action, 0, GCMD_HIGH },*/
  { "path", 251, POSITION_DEAD, do_path, 0, GCMD_HIGH },
  { "dispel", 252, POSITION_RESTING, do_dispel, 1, 0 },
  { "leeches", 253, POSITION_SLEEPING, do_ongoing_mana, 1, 0 },
  { "create", 254, POSITION_STANDING, do_create, 0, GCMD_REDIT },
  { "poofin", 255, POSITION_STANDING, do_poofin, 0, GCMD_POOF },
  { "poofout", 256, POSITION_STANDING, do_poofout, 0, GCMD_POOF },
  { "vis", 257, POSITION_RESTING, do_invis, 1, 0 },
  { "split", 258, POSITION_RESTING, do_split, 1, 0 },
  { "spells", 259, POSITION_SLEEPING, do_myspells, 1, 0 },
  { "berserk", 260, POSITION_FIGHTING, do_berserk, 1, 0 },
  { "zzitre", 261, POSITION_RESTING, do_action, 0, 0 },
  { "flirt", 262, POSITION_RESTING, do_action, 0, 0 },
  { "disagree", 263, POSITION_RESTING, do_action, 0, 0 },
  { "duck", 264, POSITION_RESTING, do_action, 0, 0 },
  { "duh", 265, POSITION_RESTING, do_action, 0, 0 },
  { "flash", 266, POSITION_RESTING, do_action, 0, 0 },
  { "flex", 267, POSITION_RESTING, do_action, 0, 0 },
  { "flipoff", 268, POSITION_RESTING, do_action, 0, 0 },
  { "froth", 269, POSITION_RESTING, do_action, 0, 0 },
  { "gibber", 270, POSITION_RESTING, do_action, 0, 0 },
  { "gloat", 271, POSITION_RESTING, do_action, 0, 0 },
  { "grimace", 272, POSITION_RESTING, do_action, 0, 0 },
  { "grumble", 273, POSITION_RESTING, do_action, 0, 0 },
  { "grunt", 274, POSITION_RESTING, do_action, 0, 0 },
  { "guffaw", 275, POSITION_RESTING, do_action, 0, 0 },
  { "hop", 276, POSITION_RESTING, do_action, 0, 0 },
  { "hum", 277, POSITION_RESTING, do_action, 0, 0 },
  { "howl", 278, POSITION_RESTING, do_action, 0, 0 },
  { "bum", 279, POSITION_RESTING, do_action, 0, 0 },
  { "ignore", 280, POSITION_RESTING, do_action, 0, 0 },
  { "scratch", 281, POSITION_RESTING, do_action, 0, 0 },
  { "jump", 282, POSITION_STANDING, do_action, 0, 0 },
  { "rkick", 283, POSITION_STANDING, do_action, 0, 0 },
  { "mock", 284, POSITION_RESTING, do_action, 0, 0 },
  { "pant", 285, POSITION_RESTING, do_action, 0, 0 },
  { "suck", 286, POSITION_RESTING, do_action, 0, 0 },
  { "putz", 287, POSITION_RESTING, do_action, 0, 0 },
  { "puzzle", 288, POSITION_RESTING, do_action, 0, 0 },
  { "recoil", 289, POSITION_RESTING, do_action, 0, 0 },
  { "roll", 290, POSITION_RESTING, do_action, 0, 0 },
  { "tongue", 291, POSITION_RESTING, do_action, 0, 0 },
  { "spank", 292, POSITION_RESTING, do_action, 0, 0 },
  { "startle", 293, POSITION_RESTING, do_action, 0, 0 },
  { "tackle", 294, POSITION_RESTING, do_action, 0, 0 },
  { "tap", 295, POSITION_RESTING, do_action, 0, 0 },
  { "taunt", 296, POSITION_FIGHTING, do_taunt, 1, 0 },
  { "whine", 297, POSITION_RESTING, do_action, 0, 0 },
  { "yuck", 298, POSITION_RESTING, do_action, 0, 0 },
  { "compose", 299, POSITION_RESTING, do_action, 0, 0 },
  { "piss", 301, POSITION_RESTING, do_action, 0, 0 },
  { "shit", 302, POSITION_RESTING, do_action, 0, 0 },
  { "rock", 303, POSITION_RESTING, do_action, 0, 0 },
  { "raise", 304, POSITION_RESTING, do_action, 0, 0 },
  { "drool", 305, POSITION_RESTING, do_action, 0, 0 },
  { "ponder", 306, POSITION_RESTING, do_action, 0, 0 },
  { "bleed", 307, POSITION_RESTING, do_action, 0, 0 },
  { "beep", 308, POSITION_RESTING, do_action, 0, 0 },
  { "apologize", 309, POSITION_RESTING, do_action, 0, 0 },
  { "melt", 310, POSITION_RESTING, do_melt, 0, 0 },
  { "ack", 311, POSITION_RESTING, do_action, 0, 0 },
  { "bite", 312, POSITION_RESTING, do_action, 0, 0 },
  { "boggle", 313, POSITION_RESTING, do_action, 0, 0 },
  { "bored", 314, POSITION_RESTING, do_action, 0, 0 },
  { "cheer", 315, POSITION_RESTING, do_action, 0, 0 },
  { "caress", 316, POSITION_RESTING, do_action, 0, 0 },
  { "crumple", 317, POSITION_RESTING, do_action, 0, 0 },
  { "die", 318, POSITION_RESTING, do_action, 0, 0 },
  { "punch", 319, POSITION_RESTING, do_action, 0, 0 },
  { "commands", 320, POSITION_SLEEPING, do_commands, 0, 0 },
  { "report", 321, POSITION_RESTING, do_report, 0, 0 },
  { "zreset", 322, POSITION_SLEEPING, do_zreset, 0, GCMD_REDIT },
  { "gtell", 323, POSITION_RESTING, do_tell_group, 0, 0 },
  { "alias", 324, POSITION_DEAD, do_alias, 0, 0 },
  { "unalias", 325, POSITION_DEAD, do_unalias, 0, 0 },
  { "chameleon", 326, POSITION_STANDING, do_chameleon, 0, 0 },
  { "push", 327, POSITION_STANDING, do_push, 0, 0 },
  { "farlook", 328, POSITION_STANDING, do_farlook, 0, 0 },
  { "fire", 329, POSITION_STANDING, do_fire, 0, 0 },
  { "notch", 330, POSITION_RESTING, do_load, 0, 0 },
  { "form", 331, POSITION_FIGHTING, do_form, 0, 0 },
  { "throw", 332, POSITION_STANDING, do_throw, 0, 0 },
  { "scan", 333, POSITION_STANDING, do_scan, 0, 0 },
  { "run", 334, POSITION_STANDING, do_run, 0, 0 },
  { "cls", 335, POSITION_DEAD, do_cls, 0, 0 },
  { "noise", 336, POSITION_DEAD, do_beep, 0, 0 },
  { "display", 337, POSITION_DEAD, do_plrtog, 0, 0 },
  { "aggressive", 338, POSITION_DEAD, do_plrtog, 0, 0 },
  { "freeze", 339, POSITION_DEAD, do_freeze, 0, GCMD_FREEZE },
  { "exp", 340, POSITION_DEAD, do_expset, 0, GCMD_HIGH },
  { "color", 341, POSITION_DEAD, do_color, 0, 0 },
  { "mask", 342, POSITION_DEAD, do_mask, 0, GCMD_POOF },
  { "bet", 343, POSITION_SITTING, do_bet, 0, 0 },
  { "stay", 344, POSITION_SITTING, do_stay, 0, 0 },
  { "peek", 345, POSITION_SITTING, do_peek, 0, 0 },
  { "log", 346, POSITION_DEAD, do_comm, 0, GCMD_GEN },
  { "notell", 347, POSITION_DEAD, do_plrtog, 0, 0 },
  { "flags", 348, POSITION_DEAD, do_flags, 0, 0 },
  { "chomp", 349, POSITION_FIGHTING, do_purge, 0, GCMD_PURGE },
  { "autoexit", 350, POSITION_DEAD, do_plrtog, 0, 0 },
  { "helptopics", 351, POSITION_DEAD, do_helptopics, 1, 0 },
  { "csocket", 352, POSITION_DEAD, do_csocket, 0, GCMD_TRANS },
  { "tag", 353, POSITION_RESTING, do_tag, 1, 0 },
  { "viewfile", 354, POSITION_DEAD, do_viewfile, 0, GCMD_SHOW },
  { "anvil", 355, POSITION_STANDING, do_action, 0, 0 },
  { "bullshit", 356, POSITION_RESTING, do_action, 0, 0 },
  { "slurp", 357, POSITION_RESTING, do_action, 0, 0 },
  { "strip", 358, POSITION_RESTING, do_action, 0, 0 },
  { "sad", 359, POSITION_RESTING, do_action, 0, 0 },
  { "hunt", 360, POSITION_STANDING, do_hunt, 0, 0 },
  { "thrust", 361, POSITION_FIGHTING, do_thrust, 0, 0 },
  { "ration", 362, POSITION_STANDING, do_ration, 0, 0 },
  { "stun", 363, POSITION_FIGHTING, do_stun, 0, 0 },
  { "befriend", 364, POSITION_STANDING, do_animal_friendship, 0, 0 },
  { "shield", 365, POSITION_STANDING, do_spell_shield, 0, 0 },
  { "great sight", 366, POSITION_STANDING, do_great_sight, 0, 0 },
  { "retreat", 367, POSITION_FIGHTING, do_retreat, 0, 0 },
  { "phantkiller", 368, POSITION_FIGHTING, do_phantasmal_killer, 0, 0 },
  { "adrenalize", 369, POSITION_STANDING, do_adrenalize, 0, 0 },
  { "ggate", 370, POSITION_STANDING, do_gateway, 0, 0 },
  { "judge", 371, POSITION_STANDING, do_judge, 0, GCMD_JUDGE },
  { "vanish", 372, POSITION_STANDING, do_invisibility, 0, 0 },
  { "canibalize", 373, POSITION_STANDING, do_canibalize, 0, 0 },
  { "illusion", 374, POSITION_STANDING, do_illusionary_shroud, 0, 0 },
  { "trip", 375, POSITION_FIGHTING, do_trip, 0, 0 },
  { "circle", 376, POSITION_FIGHTING, do_backstab, 0, 0 },
  { "search", 377, POSITION_STANDING, do_search, 0, 0 },
  { "more", 378, POSITION_DEAD, do_more, 0, 0 },
  { "levitate", 379, POSITION_STANDING, do_levitate, 0, 0 },
  { "cocoon", 380, POSITION_STANDING, do_cocoon, 0, 0 },
  { "shift", 381, POSITION_STANDING, do_shift, 0, 0 },
  { "drain", 382, POSITION_FIGHTING, do_drain_mana, 0, 0 },
  { "lgate", 383, POSITION_STANDING, do_gateway, 0, 0 },
  { "hypnotize", 384, POSITION_STANDING, do_hypnosis, 0, 0 },
  { "meditate", 385, POSITION_STANDING, do_meditation, 0, 0 },
  { "scry", 386, POSITION_STANDING, do_scry, 0, 0 },
  { "brew", 387, POSITION_STANDING, do_brew, 0, 0 },
  { "tan", 388, POSITION_STANDING, do_tan, 0, 0 },
  { "blast", 389, POSITION_FIGHTING, do_psi_attack, 0, 0 },
  { "layhands", 390, POSITION_FIGHTING, do_lay_on_hands, 0, 0 },
  { "warcry", 391, POSITION_FIGHTING, do_holy_warcry, 0, 0 },
  { "bless", 392, POSITION_STANDING, do_blessing, 0, 0 },
  { "hrescue", 393, POSITION_FIGHTING, do_heroic_rescue, 0, 0 },
  { "mount", 394, POSITION_STANDING, do_mount, 1, 0 },
  { "dismount", 395, POSITION_MOUNTED, do_mount, 1, 0 },
  { "ride", 396, POSITION_STANDING, do_mount, 1, 0 },
  { "doorbash", 397, POSITION_STANDING, do_doorbash, 1, 0 },
  { "auth", 398, POSITION_DEAD, do_auth, 0, GCMD_HIGH },
  { "imp", 399, POSITION_DEAD, do_comm, 0, GCMD_SNOOP },
  { "motd", 400, POSITION_DEAD, do_read_motd, 0, 0 },
  { "whod", 401, POSITION_DEAD, do_not_here, 0, GCMD_HIGH },
  { "home", 402, POSITION_DEAD, do_home, 0, GCMD_GEN },
#if USE_profile
  { "profile", 403, POSITION_DEAD, do_profile, 0, GCMD_HIGH },
#endif
  { "page", 404, POSITION_DEAD, do_page, 1, 0 },
  { "stats", 405, POSITION_DEAD, do_stats, 0, GCMD_GEN },
  { "policy", 406, POSITION_DEAD, do_policy, 0, 0 },
  { "reimb", 407, POSITION_STANDING, do_reimburse, 0, GCMD_REIMB },
/*  { "dir", 408, POSITION_DEAD, do_dir, 0, GCMD_HIGH },*/
  { "events", 409, POSITION_DEAD, do_events, 0, GCMD_HIGH },
  { "salute", 410, POSITION_STANDING, do_action, 0, 0 },
  { "heiney", 411, POSITION_STANDING, do_action, 0, 0 },
  { "counsel", 412, POSITION_SITTING, do_action, 1, 0 },
  { "yabba", 413, POSITION_SITTING, do_action, 1, 0 },
  { "name", 414, POSITION_DEAD, do_name, 1, 0 },
  { "auction", 415, POSITION_DEAD, do_auction, 1, 0 },
  { "rumor", 416, POSITION_RESTING, do_comm, 1, 0 },
  { "channels", 417, POSITION_DEAD, do_channels, 1, 0 },
  { "terrain", 418, POSITION_RESTING, do_terrain, 0},
  { "donate", 419, POSITION_STANDING, do_donate, 0},
  { "afk", 420, POSITION_SLEEPING, do_afk, 0},
  { "allow", 421, POSITION_SLEEPING, do_allow, 0, GCMD_HIGH },
  { "combust", 422, POSITION_FIGHTING, do_psi_attack, 0, 0 },
  { "thought", 423, POSITION_FIGHTING, do_psi_attack, 0, 0 },
  { "constrict", 424, POSITION_FIGHTING, do_psi_attack, 0, 0 },
  { "bind", 425, POSITION_FIGHTING, do_bind, 0, 0 },
  { "contract", 426, POSITION_FIGHTING, do_contract, 0, 0 },
  { "plate", 427, POSITION_STANDING, do_plate, 0, 0 },
  { "herolist", 428, POSITION_DEAD, do_herolist, 0, 0 },
  { "logall", 429, POSITION_DEAD, do_logall, 0, GCMD_HIGH },
  { "crash", 430, POSITION_SITTING, do_action, 1, 0 },
  { "brainstorm", 431, POSITION_FIGHTING, do_brainstorm, 0, 0 },
  { "appraise", 432, POSITION_SITTING, do_appraise, 0, 0 },
  { "player", 433, POSITION_SITTING, do_player, 0, GCMD_PLAYER },
  { "feint", 434, POSITION_FIGHTING, do_feint, 0, 0 },
  { "wizrep", 435, POSITION_SITTING, do_wizrep, 0, GCMD_HIGH },
  { "limb", 436, POSITION_STANDING, do_limb, 0, 0 },
  { "palm", 437, POSITION_STANDING, do_palm, 0, 0 },
  { "sample", 438, POSITION_STANDING, do_sample, 0, 0 },
  { "laston", 439, POSITION_DEAD, do_laston, 1, 0 },
  { "zonehelp", 440, POSITION_DEAD, do_zones, 1, 0 },
  { "gcomm", 441, POSITION_RESTING, do_comm, 0, 0 },
  { "swapzone", 442, POSITION_DEAD, do_swapzone, 0, GCMD_HIGH },
  { "ident", 443, POSITION_DEAD, do_ident, 0, GCMD_HIGH },
  { "autoloot", 444, POSITION_DEAD, do_plrtog, 1, 0 },
  { "slownames", 445, POSITION_DEAD, do_slownames, 0, GCMD_HIGH },
  { "absolve", 446, POSITION_DEAD, do_absolve, 0, GCMD_ABSOLVE },
  { "shadow", 447, POSITION_RESTING, do_follow, 0, 0 },

  /* added by Min 1996 for Ban Code */
  { "ban", 448, POSITION_DEAD, do_ban, 0, GCMD_BAN },
  { "unban", 449, POSITION_DEAD, do_unban, 0, GCMD_BAN },
  { "doh", 450, POSITION_RESTING, do_action, 0, 0 },
  { "tango", 451, POSITION_RESTING, do_action, 0, 0 },
  { "zerbert", 452, POSITION_RESTING, do_action, 0, 0 },
  { "rofl", 453, POSITION_SITTING, do_action, 0, 0 },

  /* added by Min 1996 for MobProgs */
  { "mpstat", 454, POSITION_DEAD, do_mpstat, 0, 0 },
  { "mpjunk", 455, POSITION_DEAD, do_mpjunk, 0, 0 },
  { "mpkill", 456, POSITION_DEAD, do_mpkill, 0, 0 },
  { "mpload", 457, POSITION_DEAD, do_mpload, 0, 0 },
  { "mppurge", 458, POSITION_DEAD, do_mppurge, 0, 0 },
  { "mpgoto", 459, POSITION_DEAD, do_mpgoto, 0, 0 },
  { "mpat", 460, POSITION_DEAD, do_mpat, 0, 0 },
  { "mptransfer", 461, POSITION_DEAD, do_mptransfer, 0, 0 },
  { "mpforce", 462, POSITION_DEAD, do_mpforce, 0, 0 },
  { "mpsend", 463, POSITION_DEAD, do_mpsend, 0, 0 },
  { "mpset", 464,  POSITION_DEAD, do_mpset, 0, 0 },

  { "autosplit", 454, POSITION_DEAD, do_plrtog, 1, 0 },
  { "autogold", 455, POSITION_DEAD, do_plrtog, 1, 0 },
  { "agree", 456, POSITION_RESTING, do_action, 0, 0 },
  { "hate", 457, POSITION_RESTING, do_action, 0, 0 },
  { "cross", 458, POSITION_RESTING, do_action, 0, 0 },
  { "wait", 459, POSITION_RESTING, do_action, 0, 0 },
  { "wipe", 460, POSITION_RESTING, do_action, 0, 0 },
  { "lean", 461, POSITION_RESTING, do_action, 0, 0 },
  { "bark", 462, POSITION_RESTING, do_action, 0, 0 },
  { "quack", 463, POSITION_RESTING, do_action, 0, 0 },
  { "faint", 464, POSITION_RESTING, do_action, 0, 0 },
  { "nerve", 465, POSITION_RESTING, do_action, 0, 0 },
  { "cool", 466, POSITION_RESTING, do_action, 0, 0 },
  { "lag", 467, POSITION_RESTING, do_action, 0, 0 },
  { "violin", 468, POSITION_RESTING, do_action, 0, 0 },
  { "believe", 469, POSITION_RESTING, do_action, 0, 0 },
  { "sneer", 470, POSITION_RESTING, do_action, 0, 0 },
  { "dig", 471, POSITION_RESTING, do_action, 0, 0 },
  { "smoke", 472, POSITION_RESTING, do_action, 0, 0 },
  { "party", 473, POSITION_RESTING, do_action, 0, 0 },
  { "catcall", 474, POSITION_RESTING, do_action, 0, 0 },
  { "yeehaw", 475, POSITION_RESTING, do_action, 0, 0 },
  { "ouch", 476, POSITION_RESTING, do_action, 0, 0 },
  { "clueless", 477, POSITION_RESTING, do_action, 0, 0 },
  { "mosh", 478, POSITION_RESTING, do_action, 0, 0 },
  { "temple", 479, POSITION_RESTING, do_temple, 0, 0 },
  { "rub", CMD_RUB, POSITION_RESTING, do_action, 0, 0 },
  { "check", CMD_CHECK, POSITION_STANDING, do_mail_check, 0, 0 },
  { "post", CMD_SEND, POSITION_STANDING, do_mail_send, 0, 0 },
  { "receive", CMD_RECEIVE, POSITION_STANDING, do_mail_receive, 0, 0 },
  { "checkin", CMD_CHECKIN, POSITION_STANDING, do_not_here, 1, 0 },
  { "holler", CMD_HOLLER, POSITION_RESTING, do_comm, 1, 0 },
  { "wings", CMD_WINGS, POSITION_RESTING, do_wings, 1, 0 },
  { "gills", CMD_GILLS, POSITION_RESTING, do_gills, 1, 0 },
/*  { "trace", CMD_TRACE, POSITION_RESTING, do_trace, 1, GCMD_HIGH },*/
  { "songs", CMD_SONGS, POSITION_SLEEPING, do_mysongs, 1, 0},
  { "guild", CMD_GUILDS, POSITION_SITTING, do_guild, 1, 0 },
  //{ "uptime", 491, POSITION_RESTING, do_uptime, 1, GCMD_HIGH },
  { "flail", 492, POSITION_FIGHTING, do_flail, 1, 0 },
  { "divert", 493, POSITION_FIGHTING, do_divert, 1, 0},
  { "gouge", 494, POSITION_FIGHTING, do_gouge, 1, 0},
  { "tolerance", 495, POSITION_STANDING, do_tolerance, 1, 0},
  { "ego", 496, POSITION_STANDING, do_ego_whip, 1, 0},
  { "awe", 497, POSITION_FIGHTING, do_awe, 1,0},
  { "spunch", 498, POSITION_FIGHTING, do_shield_punch, 1, 0},
  { "listwiz",499, POSITION_DEAD, do_wizlist, 0, GCMD_HIGH},
  { ";", 500, POSITION_RESTING, do_comm, 0, GCMD_GEN },
  { "wizset",501,POSITION_RESTING, do_wizset,0,GCMD_WIZSET},
  { "wizcomm",502,POSITION_RESTING, do_wizcomm,0, GCMD_WIZSET},
  { "quest",503,POSITION_RESTING, do_comm, 1, 0},
  { "swear",504,POSITION_RESTING, do_comm, 1, 0},
  { "trivia", 505, POSITION_RESTING, do_comm, 1, 0 },
  { "qcontrol",506, POSITION_DEAD, do_qcontrol, 0, GCMD_GEN },
  { "rpsay", 507, POSITION_RESTING, do_rpsay, 0, 0 },
  { "teleport", 508, POSITION_SLEEPING, do_teleport, 0, GCMD_TRANS },
  { "twstory", 509, POSITION_SLEEPING, do_twstory, 0, 0 },
  { "setlog", 510, POSITION_SLEEPING, do_setlog, 0, GCMD_GEN },
  { "reincarnate", 511, POSITION_SLEEPING, do_remort, 0, GCMD_SET },
  { "pkill", 512, POSITION_SLEEPING, do_pkill, 0, 0 },
  { "questup", 513, POSITION_STANDING, do_questup, 0, GCMD_REDIT },
  { "duplicate", 514, POSITION_STANDING, do_dup, 0, GCMD_REDIT },
  { "explode", 515, POSITION_FIGHTING, do_explode, 1, 0 },
  { "fedit", 516, POSITION_SLEEPING, do_fedit, 0, GCMD_REDIT },
  { "fsave", 517, POSITION_SLEEPING, do_fsave, 0, GCMD_REDIT },
//  { "bstat", 518, POSITION_STANDING, do_builder_stat, 0, GCMD_REDIT },
  { "qfunc", 519, POSITION_SLEEPING, do_qfunction, 0, 0 },
  { "rop", 520, POSITION_RESTING, do_action, 0, 0 },
  { "cad", 521, POSITION_RESTING, do_action, 0, 0 },
  { "scatter", 522, POSITION_STANDING, do_scatter, 0, GCMD_TRANS },
  { "reply", 523, POSITION_RESTING, do_reply, 0, 0 },
  { "greet", 524, POSITION_RESTING, do_action, 0, 0 },
  { "restring", 525, POSITION_STANDING, do_restring, 0, 0 },
  { "fiddle", 526, POSITION_DEAD, do_fiddle, 0, GCMD_REDIT },
  { "deny", 527, POSITION_DEAD, do_deny, 0, GCMD_TRANS },
  { "meteor", 528, POSITION_DEAD, do_zap, 0, GCMD_HIGH },
  { "compare", 529, POSITION_RESTING, do_compare, 0, 0 },
  { "make", 530, POSITION_DEAD, do_generate, 0, GCMD_GEN },
  { "vprint", 531, POSITION_DEAD, do_vprint, 0, 0 },
  { "mptrack", 532, POSITION_STANDING, do_mptrackgo, 0, 0 },
  { "mpotrack", 533, POSITION_STANDING, do_mptrackgo, 0, 0 },
  { "mpquestup", 534, POSITION_DEAD, do_mpquestup, 0, 0 },
  { "inscribe", 535, POSITION_STANDING, do_inscribe_spellbook, 0, GCMD_HIGH },
  { "pulse", 536, POSITION_FIGHTING, do_pulse_skill, 0, 0 },
  { "aura", 537, POSITION_FIGHTING, do_aura, 0, 0 },
  { "trap", 538, POSITION_STANDING, do_set_trap, 0, 0},
  { "calculate", 540, POSITION_DEAD, do_calculate, 0, 0},
  { "rewiz", 541, POSITION_DEAD, do_rewiz, 0, GCMD_HIGH},
  { "rprumor",542,POSITION_RESTING, do_comm, 1, 0},
  { "probe", 543, POSITION_SITTING, do_probe, 0, 0},
  { "imotd", 544, POSITION_DEAD, do_read_imotd, 0, GCMD_GEN },
  { "neck", 545, POSITION_STANDING, do_action, 0, 0 },
  { "brujah", 546, POSITION_SLEEPING, do_comm, 1, 0},
  { "pinch", 547, POSITION_FIGHTING, do_pinch, 0, 0},
  { "newbie", 548, POSITION_RESTING, do_comm, 1, 0},
  { "gattack", 549, POSITION_FIGHTING, do_group_attack, 0, 0 },
  { "allskills", 550, POSITION_DEAD, do_spells, 0, 0},
  { "charge", 551, POSITION_STANDING, do_charge_elements, 0, 0 },
  { "mkick", 552, POSITION_FIGHTING, do_mkick, 0, 0},
  { "lose", 553, POSITION_STANDING, do_lose, 0, 0},
  { "opstat", 554, POSITION_DEAD, do_opstat, 0, 0},
  { "rpstat", 555, POSITION_DEAD, do_rpstat, 0, 0},
  { "gold", 556, POSITION_SLEEPING, do_gold, 0, 0},
  { "affects", 557, POSITION_DEAD, do_affect, 0, 0},
  { "summon", 558, POSITION_DEAD, do_plrtog, 0, 0},
  { "find", 559, POSITION_DEAD, do_find, 0, GCMD_GEN },
  { "autoassist", 560, POSITION_DEAD, do_plrtog, 1, 0 },

  /* added by Timus 2003 */
  { "pet", 561, POSITION_STANDING, do_action, 0, 0 },
  { "bungee", 562, POSITION_STANDING, do_action, 0, 0 },
  { "spy", 563, POSITION_STANDING, do_action, 0, 0 },
  { "zexit", 564, POSITION_DEAD, do_zexit, 0, GCMD_GEN },

  /* added by Raist 2005 for voting on a hero */
  { "vote", 565, POSITION_DEAD, do_vote, 1, 0 },
  { "nominate", 566, POSITION_DEAD, do_nominate, 0, GCMD_GEN },
  { "points", 567, POSITION_DEAD, do_points, 1, 0 },

  /*added by mtr 02/04/2005 */
  { "fury", 568, POSITION_FIGHTING, do_fury, 0, 0 },

  /* added by Dar - 2010 */
  { "forge", 570, POSITION_STANDING, do_forge, 0, 0 },

  { 0 }
};

