#ifndef ENG_PROCS_H
#define ENG_PROCS_H

#define MAKE_ENG_PROC(name) \
    int logic_##name(struct char_data* ch, struct char_data* vict); \
    void pre_##name(struct char_data* ch, struct char_data* vict);

/* spells */
MAKE_ENG_PROC(acid_blast)
MAKE_ENG_PROC(acid_rain)
MAKE_ENG_PROC(ansum)
MAKE_ENG_PROC(blindness)
MAKE_ENG_PROC(blur)
MAKE_ENG_PROC(burning_hands)
MAKE_ENG_PROC(call_lightning)
MAKE_ENG_PROC(camouflage)
MAKE_ENG_PROC(chain_electrocution)
MAKE_ENG_PROC(chill_touch)
MAKE_ENG_PROC(creeping_doom)
MAKE_ENG_PROC(cure_blind)
MAKE_ENG_PROC(cure_critic)
MAKE_ENG_PROC(cure_light)
MAKE_ENG_PROC(cure_serious)
MAKE_ENG_PROC(curse)
MAKE_ENG_PROC(decay)
MAKE_ENG_PROC(disintegrate)
MAKE_ENG_PROC(dispel_magic)
MAKE_ENG_PROC(earthquake)
MAKE_ENG_PROC(electric_fire)
MAKE_ENG_PROC(electrocute)
MAKE_ENG_PROC(energy_drain)
MAKE_ENG_PROC(faerie_fire)
MAKE_ENG_PROC(fear)
MAKE_ENG_PROC(fire_wind)
MAKE_ENG_PROC(fireball)
MAKE_ENG_PROC(fireshield)
MAKE_ENG_PROC(energyshield)
MAKE_ENG_PROC(elecshield)
MAKE_ENG_PROC(poisonshield)
MAKE_ENG_PROC(coldshield)
MAKE_ENG_PROC(vampshield)
MAKE_ENG_PROC(acidshield)
MAKE_ENG_PROC(manashield)
MAKE_ENG_PROC(moveshield)
MAKE_ENG_PROC(flamestrike)
MAKE_ENG_PROC(friends)
MAKE_ENG_PROC(frost_cloud)
MAKE_ENG_PROC(geyser)
MAKE_ENG_PROC(harmful_touch)
MAKE_ENG_PROC(heal)
MAKE_ENG_PROC(ice_storm)
MAKE_ENG_PROC(implode)
MAKE_ENG_PROC(invisibility)
MAKE_ENG_PROC(lava_storm)
MAKE_ENG_PROC(lullabye)
MAKE_ENG_PROC(despair)
MAKE_ENG_PROC(slow)
MAKE_ENG_PROC(inspire)
MAKE_ENG_PROC(terror)
MAKE_ENG_PROC(monsum)
MAKE_ENG_PROC(paralyze)
MAKE_ENG_PROC(poison)
MAKE_ENG_PROC(poison_gas)
MAKE_ENG_PROC(refresh)
MAKE_ENG_PROC(remove_curse)
MAKE_ENG_PROC(remove_poison)
MAKE_ENG_PROC(rupture)
MAKE_ENG_PROC(sanctuary)
MAKE_ENG_PROC(shocking_grasp)
MAKE_ENG_PROC(silence)
MAKE_ENG_PROC(sleep)
MAKE_ENG_PROC(sunray)
MAKE_ENG_PROC(teleport)
MAKE_ENG_PROC(thorn)
MAKE_ENG_PROC(turn)
MAKE_ENG_PROC(vampyric_touch)
MAKE_ENG_PROC(vine)
MAKE_ENG_PROC(weakness)
MAKE_ENG_PROC(web)
MAKE_ENG_PROC(wind_storm)

/* skills */
MAKE_ENG_PROC(backstab)
MAKE_ENG_PROC(bash)
MAKE_ENG_PROC(trip)
MAKE_ENG_PROC(berserk)
MAKE_ENG_PROC(disarm)
MAKE_ENG_PROC(illusionary_shroud)
MAKE_ENG_PROC(hide)
MAKE_ENG_PROC(holy_warcry)
MAKE_ENG_PROC(kick)
MAKE_ENG_PROC(lay_on_hands)
MAKE_ENG_PROC(phantasmal)
MAKE_ENG_PROC(psionic_blast)
MAKE_ENG_PROC(sneak)
MAKE_ENG_PROC(spell_shield)
MAKE_ENG_PROC(stun)
MAKE_ENG_PROC(thrust)
MAKE_ENG_PROC(vanish)
MAKE_ENG_PROC(tolerance)

#endif
