
#ifndef SPELL_PROCS_H
#define SPELL_PROCS_H

void spell_poly_self(ubyte level, struct char_data *ch, int type,
   struct char_data *mob, struct obj_data *obj, int poly_type);
void cast_poly_self(ubyte level, struct char_data* ch, char* arg, int type,
   struct char_data* vict, struct obj_data* tar_obj);

#define MAKE_SPELL(name) \
    void cast_##name(ubyte level, struct char_data* ch, char* arg, int type, \
                     struct char_data* vict, struct obj_data* tar_obj); \
    void spell_##name(ubyte level, struct char_data* ch, int type, \
                      struct char_data* vict, struct obj_data* obj); 

MAKE_SPELL(ward_fire)
MAKE_SPELL(ward_cold)
MAKE_SPELL(ward_elec)
MAKE_SPELL(ward_energy)
MAKE_SPELL(ward_acid)
MAKE_SPELL(stone_fist)

MAKE_SPELL(acid_blast)
MAKE_SPELL(acid_breath)
MAKE_SPELL(acid_breath_aff)
MAKE_SPELL(acid_rain)
MAKE_SPELL(animate_dead)
MAKE_SPELL(ansum)
MAKE_SPELL(ansum)
MAKE_SPELL(armor)
MAKE_SPELL(armor_group)
MAKE_SPELL(astral_walk)
MAKE_SPELL(astral_group)  
MAKE_SPELL(bless)
MAKE_SPELL(blessing)
MAKE_SPELL(blindness)
MAKE_SPELL(blur)
MAKE_SPELL(burning_hands)
MAKE_SPELL(call_lightning)
MAKE_SPELL(calm)
MAKE_SPELL(camouflage)
MAKE_SPELL(chain_electrocution)
MAKE_SPELL(charm)
MAKE_SPELL(chill_touch)
MAKE_SPELL(clone)
MAKE_SPELL(conjure_elemental)
MAKE_SPELL(continual_light)
MAKE_SPELL(continual_dark)
MAKE_SPELL(control_weather)
MAKE_SPELL(create_food)
MAKE_SPELL(create_water)
MAKE_SPELL(creation)
MAKE_SPELL(creep)
MAKE_SPELL(cure_blind)
MAKE_SPELL(cure_critic)
MAKE_SPELL(cure_light)
MAKE_SPELL(cure_light_group)
MAKE_SPELL(cure_serious)
MAKE_SPELL(curse)
MAKE_SPELL(decay)
MAKE_SPELL(detect_invisibility)
MAKE_SPELL(detect_magic)
MAKE_SPELL(detect_poison)
MAKE_SPELL(dinvis_group)
MAKE_SPELL(disintegrate)
MAKE_SPELL(dispel_magic)
MAKE_SPELL(earthquake)
MAKE_SPELL(electric_fire)
MAKE_SPELL(electrocute)
MAKE_SPELL(empathic_heal)
MAKE_SPELL(enchant_weapon)
MAKE_SPELL(energy_drain)
MAKE_SPELL(faerie_fire)
MAKE_SPELL(faerie_fog)
MAKE_SPELL(fear)
MAKE_SPELL(fire_breath)
MAKE_SPELL(fire_breath_aff)
MAKE_SPELL(fire_wind)
MAKE_SPELL(fireball)
MAKE_SPELL(fireshield)
MAKE_SPELL(vampshield)
MAKE_SPELL(manashield)
MAKE_SPELL(elecshield)
MAKE_SPELL(coldshield)
MAKE_SPELL(energyshield)
MAKE_SPELL(poisonshield)
MAKE_SPELL(acidshield)
MAKE_SPELL(moveshield)
MAKE_SPELL(flamestrike)
MAKE_SPELL(fly_group)
MAKE_SPELL(flying)
MAKE_SPELL(friends)
MAKE_SPELL(frost_breath)
MAKE_SPELL(frost_breath_aff)
MAKE_SPELL(frost_cloud)
MAKE_SPELL(geyser)
MAKE_SPELL(golem)
MAKE_SPELL(goodberry)
MAKE_SPELL(harmful_touch)
MAKE_SPELL(haste)
MAKE_SPELL(heal)
MAKE_SPELL(heal_group)
MAKE_SPELL(regen)
MAKE_SPELL(heat_metal)
MAKE_SPELL(heroes_feast)
MAKE_SPELL(ice_storm)
MAKE_SPELL(identify)
MAKE_SPELL(implode)
MAKE_SPELL(infravision)
MAKE_SPELL(invis_group)
MAKE_SPELL(invisibility)
MAKE_SPELL(knock)
MAKE_SPELL(knowledge)
MAKE_SPELL(lava_storm)
MAKE_SPELL(light)
MAKE_SPELL(lightning_breath)
MAKE_SPELL(lightning_breath_aff)
MAKE_SPELL(lullabye)
MAKE_SPELL(inspire)
MAKE_SPELL(despair)
MAKE_SPELL(slow)
MAKE_SPELL(major_track)
MAKE_SPELL(mana)
MAKE_SPELL(minor_track)
MAKE_SPELL(monsum)
MAKE_SPELL(moonbeam)
MAKE_SPELL(mount)
MAKE_SPELL(nature_walk)
MAKE_SPELL(paralyze)
MAKE_SPELL(petrify)
MAKE_SPELL(poison)
MAKE_SPELL(poison_gas)
MAKE_SPELL(poison_gas_breath)
MAKE_SPELL(poison_gas_breath_aff)
MAKE_SPELL(possession)
MAKE_SPELL(ray_of_purification)
MAKE_SPELL(recall_group)
MAKE_SPELL(refresh)
MAKE_SPELL(remove_curse)
MAKE_SPELL(remove_paralysis)
MAKE_SPELL(remove_poison)
MAKE_SPELL(resurrection)
MAKE_SPELL(rot)
MAKE_SPELL(rupture)
MAKE_SPELL(sanctuary)
MAKE_SPELL(sense_aura)
MAKE_SPELL(sense_life)
MAKE_SPELL(shield)
MAKE_SPELL(shocking_grasp)
MAKE_SPELL(silence)
MAKE_SPELL(sleep)
MAKE_SPELL(stone_skin)
MAKE_SPELL(strength)
MAKE_SPELL(succor)
MAKE_SPELL(summon)
MAKE_SPELL(sunray)
MAKE_SPELL(teleport)
MAKE_SPELL(terror)
MAKE_SPELL(thorn)
MAKE_SPELL(tree)
MAKE_SPELL(true_seeing)
MAKE_SPELL(true_seeing_group)
MAKE_SPELL(turn)
MAKE_SPELL(vampyric_touch)
MAKE_SPELL(vine)
MAKE_SPELL(waindwalk)
MAKE_SPELL(water_breath)
MAKE_SPELL(waterbreath_group)
MAKE_SPELL(weakness)
MAKE_SPELL(web)
MAKE_SPELL(wind_storm)
MAKE_SPELL(windwalk)
MAKE_SPELL(word_of_recall)
MAKE_SPELL(unweave)
MAKE_SPELL(enforest)
MAKE_SPELL(harden_weapon)
MAKE_SPELL(gust)
MAKE_SPELL(inferno)

void cast_locate_object(ubyte level, struct char_data* ch, char* arg, int type,
                        struct char_data* tar_ch, struct obj_data* tar_obj);
void spell_locate_object(ubyte level, struct char_data* ch, int type,
                         struct char_data* victim, obj_data* obj);

void cast_minor_track(ubyte level, struct char_data *ch, char *arg, int type,
                      struct char_data *tar_ch, struct obj_data *tar_obj);
void cast_major_track(ubyte level, struct char_data *ch, char *arg, int type,
                      struct char_data *tar_ch, struct obj_data *tar_obj);
void spell_track(ubyte level, struct char_data *ch, int type,
                 struct char_data *victim, int major);

#endif
